[package]
name = "own_shell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.25.0"
termion = "1.5.6"
unicode-width = "0.1.9"
ctrlc = "3.2.2"
